[licenses]
version = 2
allow = [
    "Apache-2.0",
    "MIT",
    "BSD-2-Clause",
    "BSD-3-Clause", # BSD 3-Clause - used by subtle crate
    "ISC",          # ISC License - used by ring, rustls-webpki, untrusted
    "0BSD",         # BSD Zero Clause License - used by embassy-net dependencies
    "Unicode-3.0",
    "MPL-2.0",      # Mozilla Public License 2.0 - used by colored crate (CLI only)
    "OpenSSL",      # OpenSSL License - used by aws-lc-sys (transitive via rumqttc/rustls)
]

confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "allow"

[advisories]
version = 2
yanked = "warn"
# rustls-pemfile is unmaintained but not vulnerable - waiting for rumqttc to migrate
# See: https://github.com/rustls/pemfile/issues/61
ignore = [
    "RUSTSEC-2025-0134", # rustls-pemfile unmaintained (transitive via rumqttc)
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
    "https://github.com/embassy-rs/stm32-data-generated", # Required for embassy-stm32
]
